---
version : '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lyrics_app
    ports:
    - 5432:5432
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
    - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/lyrics_app
    - SECRET_KEY=dev-secret
    - DEBUG=false
    ports:
    - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
    - .:/app
volumes :
  pgdata: {}
